version: '3.9'

services:
  dev:
    build:
      context: ./
      target: ros_dev
    container_name: ros-dev
    environment:
      - "ROS_MASTER_URI=http://dev:11311"
      - "ROS_HOSTNAME=dev"
    volumes:
      - ./workspaces/:/workspaces/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    tty: true
    ports:
      - "6080:6080"
      - "11311:11311"
      - "33690:33690"
    command: stdbuf -o L roscore & bash -c "/start_novnc.sh"
    networks:
      - ros
networks:
  ros:
    driver: bridge
