version: '3.9'

services:

  master:
    build:
      context: ./
      target: ros_base
    container_name: ros-master
    ports:
      - "11311:11311"
      - "33690:33690"
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
    command: stdbuf -o L roscore
    networks:
      - ros
  dev:
    build:
      context: ./
      target: ros_dev
    container_name: ros-dev
    depends_on:
      - master
    environment:
      - "ROS_MASTER_URI=http://${MASTER_HOSTNAME:-master}:11311"
      - "ROS_HOSTNAME=dev"
      - "DISPLAY=${DISPLAY}"
    volumes:
      - ./workspaces/:/workspaces/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    tty: true
    networks:
      - ros
networks:
  ros:
    driver: bridge
